2020-10-08_22-58-19: DF Exception: Sub: R1093J, Sess: 0, NameError, name 'first_of_list_list' is not defined, file: <ipython-input-4-ee368a498316>, line no: 94
2020-10-08_23-02-16: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-5-ee368a498316>, line no: 94
2020-10-08_23-03-16: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-6-ee368a498316>, line no: 94
2020-10-08_23-15-41: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-7-ee368a498316>, line no: 94
2020-10-08_23-22-50: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-8-ee368a498316>, line no: 94
2020-10-08_23-23-51: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-9-ee368a498316>, line no: 94
2020-10-08_23-25-55: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-10-ee368a498316>, line no: 94
2020-10-08_23-27-23: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-11-ee368a498316>, line no: 94
2020-10-08_23-30-44: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-12-ee368a498316>, line no: 94
2020-10-08_23-31-36: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-13-e7218482d997>, line no: 95
2020-10-08_23-32-05: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-14-5508891d47f6>, line no: 95
2020-10-14_01-15-52: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-4-f90efb7f29c1>, line no: 164
2020-10-14_01-22-42: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-5-1072f0a205f0>, line no: 167
2020-10-14_01-27-23: DF Exception: Sub: R1169P, Sess: 0, NameError, name 'pcs' is not defined, file: <ipython-input-6-08bb62af33f6>, line no: 184
2020-10-14_01-30-29: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-10-0bc1e4b0e2e1>, line no: 160
2020-10-14_01-30-31: DF Exception: Sub: R1169P, Sess: 1, BdbQuit, , file: <ipython-input-10-0bc1e4b0e2e1>, line no: 160
2020-10-14_01-33-03: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-14-0bc1e4b0e2e1>, line no: 181
2020-10-15_01-07-11: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'recall_minimum' is not defined, file: <ipython-input-25-ed7d507a4bdd>, line no: 196
2020-10-15_01-07-11: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'recall_minimum' is not defined, file: <ipython-input-25-ed7d507a4bdd>, line no: 196
2020-10-15_01-13-07: DF Exception: Sub: R1334T, Sess: 0, IndexError, boolean index did not match indexed array along dimension 0; dimension is 56 but corresponding boolean dimension is 80, file: <ipython-input-26-037d89b6f669>, line no: 452
2020-10-15_01-13-36: DF Exception: Sub: R1368T, Sess: 0, IndexError, boolean index did not match indexed array along dimension 0; dimension is 16 but corresponding boolean dimension is 26, file: <ipython-input-26-037d89b6f669>, line no: 452
2020-10-15_02-08-39: DF Exception: Sub: R1334T, Sess: 0, IndexError, list index out of range, file: <ipython-input-4-57cbb0c1efc4>, line no: 172
2020-10-15_02-08-40: DF Exception: Sub: R1368T, Sess: 0, IndexError, list index out of range, file: <ipython-input-4-57cbb0c1efc4>, line no: 172
2020-10-16_18-26-57: DF Exception: Sub: R1334T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-4-5f750472c544>, line no: 135
2020-10-16_18-26-57: DF Exception: Sub: R1368T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-4-5f750472c544>, line no: 135
2020-10-16_18-27-09: DF Exception: Sub: R1334T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-5-5f750472c544>, line no: 135
2020-10-16_18-27-09: DF Exception: Sub: R1368T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-5-5f750472c544>, line no: 135
2020-10-16_18-30-39: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-6-08229a458f5a>, line no: 141
2020-10-16_18-30-41: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-08229a458f5a>, line no: 141
2020-10-16_18-34-23: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-7-f7bc5d297c14>, line no: 148
2020-10-16_18-34-25: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-7-f7bc5d297c14>, line no: 141
2020-10-16_19-22-19: DF Exception: Sub: R1334T, Sess: 0, TypeError, unsupported operand type(s) for -: 'list' and 'int', file: <ipython-input-15-3ad3bb6602c3>, line no: 155
2020-10-16_19-22-19: DF Exception: Sub: R1368T, Sess: 0, TypeError, unsupported operand type(s) for -: 'list' and 'int', file: <ipython-input-15-3ad3bb6602c3>, line no: 155
2020-10-16_19-22-51: DF Exception: Sub: R1334T, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-16-79d85da2b608>, line no: 175
2020-10-16_19-24-49: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-16-79d85da2b608>, line no: 173
2020-10-16_22-57-20: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-4-375a8a7ee21e>, line no: 202
2020-10-16_22-57-25: DF Exception: Sub: R1368T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-4-375a8a7ee21e>, line no: 202
2020-10-16_23-19-56: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-5-375a8a7ee21e>, line no: 202
2020-10-16_23-21-32: DF Exception: Sub: R1368T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-5-375a8a7ee21e>, line no: 202
2020-10-16_23-38-25: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-6-361e3f939ad9>, line no: 202
2020-10-16_23-39-54: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-361e3f939ad9>, line no: 202
2020-10-16_23-42-06: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-7-361e3f939ad9>, line no: 202
2020-10-16_23-44-36: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-7-361e3f939ad9>, line no: 202
2020-10-16_23-49-08: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-8-361e3f939ad9>, line no: 202
2020-10-16_23-49-08: DF Exception: Sub: R1368T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-8-361e3f939ad9>, line no: 202
2020-10-16_23-50-00: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-9-361e3f939ad9>, line no: 202
2020-10-16_23-53-03: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-9-361e3f939ad9>, line no: 202
2020-10-16_23-54-09: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-10-361e3f939ad9>, line no: 202
2020-10-16_23-54-10: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-10-361e3f939ad9>, line no: 202
2020-10-16_23-55-47: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-11-361e3f939ad9>, line no: 226
2020-10-16_23-55-49: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-11-361e3f939ad9>, line no: 226
2020-10-17_01-30-09: DF Exception: Sub: R1334T, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-15-c2e46f9be4bf>, line no: 227
2020-10-17_01-30-09: DF Exception: Sub: R1368T, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-15-c2e46f9be4bf>, line no: 227
2020-10-17_01-31-57: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-16-c2e46f9be4bf>, line no: 227
2020-10-17_01-31-58: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-16-c2e46f9be4bf>, line no: 227
2020-10-17_01-51-45: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-18-1af58cf94437>, line no: 131
2020-10-17_01-51-45: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-18-1af58cf94437>, line no: 131
2020-10-17_01-52-09: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-19-1af58cf94437>, line no: 131
2020-10-17_01-52-09: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-19-1af58cf94437>, line no: 131
2020-10-17_01-52-27: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-21-1af58cf94437>, line no: 131
2020-10-17_01-52-27: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-21-1af58cf94437>, line no: 131
2020-10-17_01-53-27: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-22-1af58cf94437>, line no: 131
2020-10-17_01-53-27: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'getSerialposOfRecalls' is not defined, file: <ipython-input-22-1af58cf94437>, line no: 131
2020-10-17_01-53-44: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'ln' is not defined, file: <ipython-input-24-1af58cf94437>, line no: 131
2020-10-17_01-53-44: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'ln' is not defined, file: <ipython-input-24-1af58cf94437>, line no: 131
2020-10-17_02-13-07: DF Exception: Sub: R1334T, Sess: 0, IndexError, list index out of range, file: <ipython-input-25-211b27af8524>, line no: 185
2020-10-17_02-13-07: DF Exception: Sub: R1368T, Sess: 0, IndexError, list index out of range, file: <ipython-input-25-211b27af8524>, line no: 185
2020-10-17_02-18-29: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'list_recalls_df' is not defined, file: <ipython-input-4-29fe11e4b46e>, line no: 217
2020-10-17_02-18-29: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'list_recalls_df' is not defined, file: <ipython-input-4-29fe11e4b46e>, line no: 217
2020-10-17_02-20-09: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'nonrepeat_idxs' is not defined, file: <ipython-input-5-29fe11e4b46e>, line no: 217
2020-10-17_02-20-09: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'nonrepeat_idxs' is not defined, file: <ipython-input-5-29fe11e4b46e>, line no: 217
2020-10-17_02-29-11: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-4-cf562e257364>, line no: 221
2020-10-17_02-29-13: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-4-cf562e257364>, line no: 221
2020-10-17_02-40-31: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-5-c658ab472995>, line no: 193
2020-10-17_02-40-32: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-5-c658ab472995>, line no: 193
2020-10-17_02-42-07: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-6-c658ab472995>, line no: 193
2020-10-17_02-42-08: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-c658ab472995>, line no: 193
2020-10-17_02-45-20: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-7-c658ab472995>, line no: 193
2020-10-17_02-45-22: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-7-c658ab472995>, line no: 193
2020-10-17_02-46-08: DF Exception: Sub: R1334T, Sess: 0, ValueError, Item wrong length 1 instead of 111., file: <ipython-input-8-c658ab472995>, line no: 221
2020-10-17_02-46-08: DF Exception: Sub: R1368T, Sess: 0, ValueError, Item wrong length 1 instead of 44., file: <ipython-input-8-c658ab472995>, line no: 221
2020-10-17_02-49-10: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-9-ceb70cddfcbe>, line no: 220
2020-10-17_02-49-11: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-9-ceb70cddfcbe>, line no: 220
2020-10-17_02-52-24: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-10-4c47e1ab6783>, line no: 194
2020-10-17_02-52-25: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-10-4c47e1ab6783>, line no: 194
2020-10-17_02-54-13: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-11-b8b520bc681f>, line no: 199
2020-10-17_02-54-15: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-11-b8b520bc681f>, line no: 194
2020-10-17_02-56-32: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-12-812e6fdb81f4>, line no: 196
2020-10-17_02-56-33: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-12-812e6fdb81f4>, line no: 196
2020-10-17_03-02-24: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-13-84e44c1c9220>, line no: 195
2020-10-17_03-02-24: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-13-84e44c1c9220>, line no: 195
2020-10-17_03-11-05: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-14-84e44c1c9220>, line no: 195
2020-10-17_03-11-06: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-14-84e44c1c9220>, line no: 195
2020-10-17_03-13-13: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-15-e744d800aaf9>, line no: 195
2020-10-17_03-13-14: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-15-e744d800aaf9>, line no: 195
2020-10-17_03-15-03: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-16-1f6f04cf0463>, line no: 216
2020-10-17_03-15-04: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-16-1f6f04cf0463>, line no: 216
2020-10-17_12-28-20: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-18-1f6f04cf0463>, line no: 216
2020-10-17_13-11-47: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-18-1f6f04cf0463>, line no: 216
2020-10-19_15-55-37: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-6-5a77eb8dc05b>, line no: 198
2020-10-19_15-55-39: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-6-5a77eb8dc05b>, line no: 198
2020-10-19_15-55-40: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-5a77eb8dc05b>, line no: 198
2020-10-19_15-59-15: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-7-5a77eb8dc05b>, line no: 198
2020-10-19_15-59-16: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-7-5a77eb8dc05b>, line no: 198
2020-10-19_15-59-17: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-7-5a77eb8dc05b>, line no: 198
2020-10-19_16-01-25: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-8-5a77eb8dc05b>, line no: 198
2020-10-19_16-01-26: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-8-5a77eb8dc05b>, line no: 198
2020-10-19_16-01-28: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-8-5a77eb8dc05b>, line no: 198
2020-10-19_16-02-32: DF Exception: Sub: R1169P, Sess: 0, IndexError, too many indices for array, file: <ipython-input-9-5a77eb8dc05b>, line no: 198
2020-10-19_16-02-52: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-9-5a77eb8dc05b>, line no: 198
2020-10-19_16-02-53: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-9-5a77eb8dc05b>, line no: 198
2020-10-19_16-40-10: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-4-5a77eb8dc05b>, line no: 198
2020-10-19_16-40-10: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-4-5a77eb8dc05b>, line no: 198
2020-10-19_16-40-11: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-4-5a77eb8dc05b>, line no: 198
2020-10-19_16-48-22: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-5-8584f59e48ec>, line no: 199
2020-10-19_16-48-22: DF Exception: Sub: R1334T, Sess: 0, IndexError, arrays used as indices must be of integer (or boolean) type, file: <ipython-input-5-8584f59e48ec>, line no: 199
2020-10-19_16-48-23: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-5-8584f59e48ec>, line no: 199
2020-10-19_16-48-54: DF Exception: Sub: R1169P, Sess: 0, ValueError, list.remove(x): x not in list, file: <ipython-input-6-407a529031ed>, line no: 198
2020-10-19_16-48-55: DF Exception: Sub: R1334T, Sess: 0, IndexError, arrays used as indices must be of integer (or boolean) type, file: <ipython-input-6-407a529031ed>, line no: 198
2020-10-19_16-50-59: DF Exception: Sub: R1169P, Sess: 0, ValueError, list.remove(x): x not in list, file: <ipython-input-4-407a529031ed>, line no: 198
2020-10-19_16-50-59: DF Exception: Sub: R1334T, Sess: 0, IndexError, arrays used as indices must be of integer (or boolean) type, file: <ipython-input-4-407a529031ed>, line no: 198
2020-10-19_16-52-21: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-4-407a529031ed>, line no: 199
2020-10-19_16-56-10: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-5-2f3f6b940c03>, line no: 198
2020-10-19_16-56-10: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-5-2f3f6b940c03>, line no: 198
2020-10-19_16-56-11: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-5-2f3f6b940c03>, line no: 198
2020-10-19_16-59-03: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-6-2f3f6b940c03>, line no: 199
2020-10-19_16-59-04: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-6-2f3f6b940c03>, line no: 199
2020-10-19_16-59-05: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-2f3f6b940c03>, line no: 199
2020-10-19_17-03-22: DF Exception: Sub: R1169P, Sess: 0, ValueError, list.remove(x): x not in list, file: <ipython-input-7-f29c5c52f41c>, line no: 198
2020-10-19_17-03-59: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-7-f29c5c52f41c>, line no: 198
2020-10-19_17-03-59: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-7-f29c5c52f41c>, line no: 198
2020-10-19_17-04-49: DF Exception: Sub: R1169P, Sess: 0, ValueError, list.remove(x): x not in list, file: <ipython-input-8-f29c5c52f41c>, line no: 198
2020-10-19_17-13-20: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'nonrepeat_idxs' is not defined, file: <ipython-input-8-f29c5c52f41c>, line no: 222
2020-10-19_17-13-46: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-8-f29c5c52f41c>, line no: 200
2020-10-19_17-13-57: DF Exception: Sub: R1169P, Sess: 0, ValueError, list.remove(x): x not in list, file: <ipython-input-9-f29c5c52f41c>, line no: 198
2020-10-19_17-14-01: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-9-f29c5c52f41c>, line no: 200
2020-10-19_17-14-02: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-9-f29c5c52f41c>, line no: 200
2020-10-19_17-29-42: DF Exception: Sub: R1169P, Sess: 0, ValueError, list.remove(x): x not in list, file: <ipython-input-10-f29c5c52f41c>, line no: 198
2020-10-19_17-29-49: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-10-f29c5c52f41c>, line no: 198
2020-10-19_17-29-50: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-10-f29c5c52f41c>, line no: 198
2020-10-19_17-35-01: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-11-f29c5c52f41c>, line no: 198
2020-10-19_17-35-02: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-11-f29c5c52f41c>, line no: 198
2020-10-19_17-35-03: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-11-f29c5c52f41c>, line no: 198
2020-10-19_17-47-55: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-12-f29c5c52f41c>, line no: 198
2020-10-19_17-47-56: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-12-f29c5c52f41c>, line no: 198
2020-10-19_17-47-57: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-12-f29c5c52f41c>, line no: 198
2020-10-19_17-50-29: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-13-f29c5c52f41c>, line no: 200
2020-10-19_17-50-30: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-13-f29c5c52f41c>, line no: 200
2020-10-19_17-50-30: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-13-f29c5c52f41c>, line no: 200
2020-10-19_18-22-44: DF Exception: Sub: R1169P, Sess: 0, NameError, name 'nonrepeat_idxs' is not defined, file: <ipython-input-14-0c1dbb767d08>, line no: 221
2020-10-19_18-23-03: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'nonrepeat_idxs' is not defined, file: <ipython-input-14-0c1dbb767d08>, line no: 221
2020-10-19_18-28-43: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-14-0c1dbb767d08>, line no: 218
2020-10-19_18-59-01: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-4-c9b64d865fef>, line no: 185
2020-10-19_18-59-01: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-4-c9b64d865fef>, line no: 185
2020-10-19_18-59-02: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-4-c9b64d865fef>, line no: 185
2020-10-19_19-06-22: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-5-8ef9c22f5081>, line no: 222
2020-10-19_19-06-24: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-5-8ef9c22f5081>, line no: 222
2020-10-19_19-06-25: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-5-8ef9c22f5081>, line no: 222
2020-10-19_19-11-51: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-6-28492c8829d4>, line no: 179
2020-10-19_19-11-52: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-6-28492c8829d4>, line no: 179
2020-10-19_19-11-53: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-28492c8829d4>, line no: 179
2020-10-19_19-19-38: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-8-52ad6c76d1a8>, line no: 179
2020-10-19_19-19-38: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-8-52ad6c76d1a8>, line no: 179
2020-10-19_19-19-39: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-8-52ad6c76d1a8>, line no: 179
2020-10-19_19-21-05: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-9-7ce0fb6c2806>, line no: 224
2020-10-19_19-21-08: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-9-7ce0fb6c2806>, line no: 224
2020-10-19_19-21-09: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-9-7ce0fb6c2806>, line no: 224
2020-10-19_19-33-05: DF Exception: Sub: R1169P, Sess: 0, KeyError, 'HEAD', file: <ipython-input-13-d5f9d6b66fc3>, line no: 157
2020-10-19_19-33-05: DF Exception: Sub: R1169P, Sess: 1, KeyError, 'HEAD', file: <ipython-input-13-d5f9d6b66fc3>, line no: 157
2020-10-19_19-33-05: DF Exception: Sub: R1334T, Sess: 0, KeyError, 'HEAD', file: <ipython-input-13-d5f9d6b66fc3>, line no: 157
2020-10-19_19-33-05: DF Exception: Sub: R1334T, Sess: 1, KeyError, 'HEAD', file: <ipython-input-13-d5f9d6b66fc3>, line no: 157
2020-10-19_19-33-05: DF Exception: Sub: R1334T, Sess: 2, KeyError, 'HEAD', file: <ipython-input-13-d5f9d6b66fc3>, line no: 157
2020-10-19_19-33-05: DF Exception: Sub: R1368T, Sess: 0, KeyError, 'HEAD', file: <ipython-input-13-d5f9d6b66fc3>, line no: 157
2020-10-19_19-39-14: DF Exception: Sub: R1169P, Sess: 0, NameError, name 'list_words_df' is not defined, file: <ipython-input-4-95db49468565>, line no: 158
2020-10-19_19-41-05: DF Exception: Sub: R1169P, Sess: 1, BdbQuit, , file: <ipython-input-4-95db49468565>, line no: 156
2020-10-19_19-41-06: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-4-95db49468565>, line no: 156
2020-10-19_19-41-07: DF Exception: Sub: R1334T, Sess: 1, BdbQuit, , file: <ipython-input-4-95db49468565>, line no: 156
2020-10-19_19-41-08: DF Exception: Sub: R1334T, Sess: 2, BdbQuit, , file: <ipython-input-4-95db49468565>, line no: 156
2020-10-19_19-41-09: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-4-95db49468565>, line no: 156
2020-10-19_20-04-51: DF Exception: Sub: R1169P, Sess: 0, NameError, name 'list_words_df' is not defined, file: <ipython-input-7-7ac5df42fd72>, line no: 160
2020-10-19_20-04-51: DF Exception: Sub: R1169P, Sess: 1, NameError, name 'list_words_df' is not defined, file: <ipython-input-7-7ac5df42fd72>, line no: 160
2020-10-19_20-04-52: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'list_words_df' is not defined, file: <ipython-input-7-7ac5df42fd72>, line no: 160
2020-10-19_20-04-52: DF Exception: Sub: R1334T, Sess: 1, NameError, name 'list_words_df' is not defined, file: <ipython-input-7-7ac5df42fd72>, line no: 160
2020-10-19_20-04-52: DF Exception: Sub: R1334T, Sess: 2, NameError, name 'list_words_df' is not defined, file: <ipython-input-7-7ac5df42fd72>, line no: 160
2020-10-19_20-04-52: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'list_words_df' is not defined, file: <ipython-input-7-7ac5df42fd72>, line no: 160
2020-10-20_22-18-15: DF Exception: Sub: R1169P, Sess: 0, NameError, name 'list_words_df' is not defined, file: <ipython-input-4-06d645d18f71>, line no: 160
2020-10-20_22-18-15: DF Exception: Sub: R1169P, Sess: 1, NameError, name 'list_words_df' is not defined, file: <ipython-input-4-06d645d18f71>, line no: 160
2020-10-20_22-18-15: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'list_words_df' is not defined, file: <ipython-input-4-06d645d18f71>, line no: 160
2020-10-20_22-18-15: DF Exception: Sub: R1334T, Sess: 1, NameError, name 'list_words_df' is not defined, file: <ipython-input-4-06d645d18f71>, line no: 160
2020-10-20_22-18-15: DF Exception: Sub: R1334T, Sess: 2, NameError, name 'list_words_df' is not defined, file: <ipython-input-4-06d645d18f71>, line no: 160
2020-10-20_22-18-15: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'list_words_df' is not defined, file: <ipython-input-4-06d645d18f71>, line no: 160
2020-10-20_22-23-18: DF Exception: Sub: R1169P, Sess: 0, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-5-c8485862f007>, line no: 169
2020-10-20_22-23-18: DF Exception: Sub: R1169P, Sess: 1, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-5-c8485862f007>, line no: 169
2020-10-20_22-23-18: DF Exception: Sub: R1334T, Sess: 0, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-5-c8485862f007>, line no: 169
2020-10-20_22-23-18: DF Exception: Sub: R1334T, Sess: 1, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-5-c8485862f007>, line no: 169
2020-10-20_22-23-18: DF Exception: Sub: R1334T, Sess: 2, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-5-c8485862f007>, line no: 169
2020-10-20_22-23-18: DF Exception: Sub: R1368T, Sess: 0, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-5-c8485862f007>, line no: 169
2020-10-20_22-53-39: DF Exception: Sub: R1169P, Sess: 0, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-6-c8485862f007>, line no: 169
2020-10-20_22-54-33: DF Exception: Sub: R1169P, Sess: 1, TypeError, '>' not supported between instances of 'list' and 'int', file: <ipython-input-6-c8485862f007>, line no: 169
2020-10-20_22-54-51: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-6-c8485862f007>, line no: 168
2020-10-20_22-54-52: DF Exception: Sub: R1334T, Sess: 1, BdbQuit, , file: <ipython-input-6-c8485862f007>, line no: 168
2020-10-20_22-54-53: DF Exception: Sub: R1334T, Sess: 2, BdbQuit, , file: <ipython-input-6-c8485862f007>, line no: 168
2020-10-20_22-54-53: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-c8485862f007>, line no: 168
2020-10-20_22-57-16: DF Exception: Sub: R1169P, Sess: 0, KeyError, 'AXE', file: <ipython-input-7-58359607fe14>, line no: 162
2020-10-20_22-57-16: DF Exception: Sub: R1169P, Sess: 1, KeyError, 'AXE', file: <ipython-input-7-58359607fe14>, line no: 162
2020-10-20_22-57-16: DF Exception: Sub: R1334T, Sess: 0, KeyError, 'AXE', file: <ipython-input-7-58359607fe14>, line no: 162
2020-10-20_22-57-16: DF Exception: Sub: R1334T, Sess: 1, KeyError, 'AXE', file: <ipython-input-7-58359607fe14>, line no: 162
2020-10-20_22-57-16: DF Exception: Sub: R1334T, Sess: 2, KeyError, 'AXE', file: <ipython-input-7-58359607fe14>, line no: 162
2020-10-20_22-57-17: DF Exception: Sub: R1368T, Sess: 0, KeyError, 'AXE', file: <ipython-input-7-58359607fe14>, line no: 162
